title: DAFFODIL
description: My Simple Rules for DnD
theme: just-the-docs
url: https://paradisebunny.github.io/daffodil/

# set dark color scheme dark/light
color_scheme: dark

# links displayed at the top right
aux_links:
  Blog: https://paradisebunny.bearblog.dev/
  itch.io: https://paradisebunny.itch.io/


# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# temporarily hached out CC-BY-SA licence
# footer_content: "The text on this page is licensed under <a href=\"https://creativecommons.org/licenses/by-sa/4.0\">CC-BY-SA 4.0.</a>"


font-family: 'Iowan Old Style', 'Palatino Linotype', 'URW Palladio L', P052, serif;
