title: Daffodil
description: My rules for playing D&D
theme: just-the-docs
url: https://paradisebunny.github.io/daffodil/

# set dark color scheme dark/light
color_scheme: light

# links displayed at the top right
aux_links:
  My Blog: https://paradisebunny.bearblog.dev/
